env:
  global:
    - CC_TEST_REPORTER_ID={id}

language: node_js
node_js:
  - '13'
  - '11'
  - '10'
  - '8'
dist: trusty
sudo: true
before_script:
  - sleep 15
  - mongo admin --eval 'db.createUser({user:"mick",pwd:"testPass",roles:[{ role:"readWrite", db:"test" }]});'
  - timedatectl set-timezone Asia/Tokyo
services:
  - mongodb
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell