module.exports = [
  'aggregate',
  'bulkWrite',
  // Deprecated 'count',
  'countDocuments',
  'createIndex',
  'createIndexes',
  'deleteMany',
  'deleteOne',
  'distinct',
  'drop',
  // Deprecated 'dropAllIndexes',
  'dropIndex',
  'dropIndexes',
  // Deprecated 'ensureIndex',
  'estimatedDocumentCount',
  'find',
  // Deprecated 'findAndModify',
  // Deprecated 'findAndRemove',
  'findOne',
  'findOneAndDelete',
  'findOneAndReplace',
  'findOneAndUpdate',
  'geoHaystackSearch',
  'getLogger',
  // Deprecated 'group',
  'indexExists',
  'indexInformation',
  'indexes',
  'initializeOrderedBulkOp',
  'initializeUnorderedBulkOp',
  // Deprecated 'insert',
  'insertMany',
  'insertOne',
  'isCapped',
  'listIndexes',
  'mapReduce',
  'options',
  'parallelCollectionScan',
  'reIndex',
  // Deprecated 'remove',
  'removeMany',
  'removeOne',
  'rename',
  'replaceOne',
  // Deprecated 'save',
  'stats',
  // Deprecated 'update',
  'updateMany',
  'updateOne',
  'watch'
]
